CREATE DATABASE IF NOT EXISTS contact_app
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE contact_app;

CREATE TABLE IF NOT EXISTS enquiries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
